name: 'Bump Package Version'
description: 'Update package.json version and commit changes'

inputs:
  new-version:
    description: 'New version to set'
    required: true
  github-token:
    description: 'GitHub token for pushing changes'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update package.json version
      shell: bash
      run: |
        NEW_VERSION='${{ inputs.new-version }}'
        echo "Updating package.json to version: $NEW_VERSION"
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.version = '$NEW_VERSION';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
        "
        echo "Updated package.json:"
        cat package.json | grep '"version"'
        
        # Commit and push the version bump
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add package.json
        git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
        git push origin ${{ github.ref_name }}
        
        # Create and push GitHub tag
        echo "Creating GitHub tag: v$NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release version $NEW_VERSION"
        git push origin "v$NEW_VERSION"
        
        echo "✅ Version bumped to $NEW_VERSION and tag v$NEW_VERSION created"
