name: 'Bump Package Version'
description: 'Update package.json version and commit changes'

inputs:
  new-version:
    description: 'New version to set'
    required: true
  github-token:
    description: 'GitHub token for pushing changes'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update package.json version
      shell: bash
      run: |
        NEW_VERSION='${{ inputs.new-version }}'
        echo "Updating package.json to version: $NEW_VERSION"
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.version = '$NEW_VERSION';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
        "
        echo "Updated package.json:"
        cat package.json | grep '"version"'
        
        # Debug branch information
        echo "Event name: ${{ github.event_name }}"
        echo "Head ref: ${{ github.head_ref }}"
        echo "Ref name: ${{ github.ref_name }}"
        echo "Ref: ${{ github.ref }}"
        
        # Commit and push the version bump
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add package.json
        git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
        
        # Push to the correct branch (PR head or direct branch)
        if [ "${{ github.event_name }}" = "pull_request" ] && [ -n "${{ github.head_ref }}" ]; then
          echo "Pushing to PR head branch: ${{ github.head_ref }}"
          git push origin ${{ github.head_ref }}
        else
          echo "Pushing to direct branch: ${{ github.ref_name }}"
          git push origin ${{ github.ref_name }}
        fi
