name: 'Validate YAML Syntax'
description: 'Validate YAML syntax for GitHub Actions workflows and custom actions'

runs:
  using: 'composite'
  steps:
    - name: Validate YAML syntax
      shell: bash
      run: |
        echo "🔍 Validating YAML syntax..."
        
        # Check main CI/CD workflow
        echo "Validating .github/workflows/ci-cd.yml..."
        python3 -c "import yaml; yaml.safe_load(open('.github/workflows/ci-cd.yml'))" || exit 1
        
        # Check rollback workflow
        echo "Validating .github/workflows/rollback.yml..."
        python3 -c "import yaml; yaml.safe_load(open('.github/workflows/rollback.yml'))" || exit 1
        
        # Check all custom action YAML files
        echo "Validating custom action YAML files..."
        find .github/actions -name "action.yml" -exec sh -c '
          echo "Validating {}..."
          python3 -c "import yaml; yaml.safe_load(open('\''{}'\''))" || exit 1
        ' \;
        
        echo "✅ All YAML files are valid!"

    - name: Validate GitHub Actions structure
      shell: bash
      run: |
        chmod +x validate.py
        python3 validate.py
