name: 'Notify Success'
description: 'Send success notifications for deployment'

inputs:
  environment:
    description: 'Environment that was deployed'
    required: true
  registry:
    description: 'Docker registry URL'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  version:
    description: 'Version that was deployed'
    required: true
  brevo-smtp-user:
    description: 'Brevo SMTP username'
    required: true
  brevo-smtp-key:
    description: 'Brevo SMTP password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Notify deployment success
      uses: actions/github-script@v6
      with:
        script: |
          // Create environment display name (capitalized)
          const environment = '${{ inputs.environment }}';
          const environmentName = environment.charAt(0).toUpperCase() + environment.slice(1);
          
          // Create deployment notification with key deployment details
          const message = `✅ **${environmentName} Deployment Successful**
          
          **Repository**: ${context.repo.owner}/${context.repo.repo}
          **Branch**: ${context.ref_name}
          **Version**: ${{ inputs.version }}
          **Commit**: ${context.sha.substring(0, 7)}
          **Triggered by**: ${context.actor}
          **Image**: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}
          
          🎉 All checks passed and ${environment} deployment completed successfully!`;
          
          // Log notification
          console.log('📢 DEPLOYMENT NOTIFICATION:');
          console.log(message);
          
          // Create GitHub comment for tracking (only for pull requests)
          if (context.eventName === 'pull_request') {
            try {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
              console.log('✅ Success comment created on PR');
            } catch (error) {
              // Graceful fallback if permissions are insufficient
              console.log('⚠️ Could not create PR comment (this is normal for some permissions)');
              console.log('Error details:', error.message);
            }
          }

    - name: Send success email notification
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ inputs.brevo-smtp-user }}
        password: ${{ inputs.brevo-smtp-key }}
        subject: "✅ ${{ inputs.environment }} Deployment Successful - ${{ github.repository }}"
        to: ${{ github.event.pusher.email }}
        from: "<shalommeoded@gmail.com>"
        body: |
          Hello ${{ github.actor }},
          
          Your deployment to ${{ inputs.environment }} environment has completed successfully!
          
          **Details:**
          - Repository: ${{ github.repository }}
          - Branch: ${{ github.ref_name }}
          - Version: ${{ inputs.version }}
          - Commit: ${{ github.sha }}
          - Environment: ${{ inputs.environment }}
          - URL: ${{ 
            inputs.environment == 'production' && 'https://myprod.getthemilkshake.com' || 
            inputs.environment == 'staging' && 'https://mystaging.getthemilkshake.com' || 
            'https://mydev.getthemilkshake.com' 
          }}
          
          🎉 All quality gates passed and deployment completed successfully!
          
          Best regards,
          CI/CD Pipeline
        convert_markdown: true
