name: 'Test & Quality Gates'
description: 'Run tests, linting, security audit, and health checks'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn install

    - name: Run linting
      shell: bash
      run: yarn lint

    - name: Run tests
      shell: bash
      run: yarn test

    - name: Run security audit
      shell: bash
      run: yarn audit --level moderate

    - name: Run health check
      shell: bash
      run: |
        yarn start &
        sleep 3
        chmod +x test.sh
        ./test.sh
        pkill -f "node server.js"
