name: 'Bump Version'
description: 'Automatically bump version based on PR labels'

inputs:
  bump-type:
    description: 'Type of version bump (patch, minor, major)'
    required: false
    default: 'auto'
  github-token:
    description: 'GitHub token for authentication'
    required: true

outputs:
  new-version:
    description: 'New version after bump'
    value: ${{ steps.bump.outputs.new-version }}
  bump-type:
    description: 'Type of bump performed'
    value: ${{ steps.bump.outputs.bump-type }}

runs:
  using: 'composite'
  steps:
    - name: Install semver dependency
      shell: bash
      run: yarn add semver

    - name: Bump version
      id: bump
      shell: bash
      run: |
        # Get current version from package.json
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: ${CURRENT_VERSION}"
        
        # Determine bump type from PR labels
        if [ "${{ inputs.bump-type }}" = "auto" ]; then
          # Check for PR labels (only works on pull_request events)
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_LABELS="${{ github.event.pull_request.labels.*.name }}"
            echo "PR Labels: ${PR_LABELS}"
            
            if echo "$PR_LABELS" | grep -q "version:major"; then
              BUMP_TYPE="major"
            elif echo "$PR_LABELS" | grep -q "version:minor"; then
              BUMP_TYPE="minor"
            elif echo "$PR_LABELS" | grep -q "version:patch"; then
              BUMP_TYPE="patch"
            else
              # Default to patch if no version label
              BUMP_TYPE="patch"
            fi
          else
            # For direct pushes, default to patch
            BUMP_TYPE="patch"
          fi
        else
          BUMP_TYPE="${{ inputs.bump-type }}"
        fi
        
        echo "Bump type: ${BUMP_TYPE}"
        
        # Bump version using semver
        NEW_VERSION=$(node -e "
          const semver = require('semver');
          const current = '$CURRENT_VERSION';
          const bumpType = '$BUMP_TYPE';
          console.log(semver.inc(current, bumpType));
        ")
        
        echo "New version: ${NEW_VERSION}"
        
        # Update package.json
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          pkg.version = '$NEW_VERSION';
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
        "
        
        # Set outputs
        echo "new-version=${NEW_VERSION}" >> $GITHUB_OUTPUT
        echo "bump-type=${BUMP_TYPE}" >> $GITHUB_OUTPUT
        
        # Commit and push version bump
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add package.json
        git commit -m "chore: bump version to ${NEW_VERSION} [skip ci]"
        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }}
        git push origin HEAD
