name: 'Notify Failure'
description: 'Send failure notifications via email and GitHub comments'

inputs:
  environment:
    description: 'Deployment environment'
    required: true
  version:
    description: 'Deployed version'
    required: true
  error:
    description: 'Error message'
    required: true
  brevo-smtp-user:
    description: 'Brevo SMTP username'
    required: true
  brevo-smtp-key:
    description: 'Brevo SMTP password'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  email-to:
    description: 'Email recipient(s)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create failure notification
      uses: actions/github-script@v6
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      with:
        script: |
          // Create environment display name (capitalized)
          const environment = '${{ inputs.environment }}';
          const environmentName = environment.charAt(0).toUpperCase() + environment.slice(1);
          
          // Create failure notification with key details
          const message = `❌ **${environmentName} Deployment Failed**
          
          **Repository**: ${context.repo.owner}/${context.repo.repo}
          **Branch**: ${context.ref_name}
          **Version**: ${{ inputs.version }}
          **Commit**: ${context.sha.substring(0, 7)}
          **Triggered by**: ${context.actor}
          **Error**: ${{ inputs.error }}
          
          🔧 Please check the [workflow logs](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}) for details.`;
          
          // Log notification
          console.log('🚨 DEPLOYMENT FAILURE NOTIFICATION:');
          console.log(message);
          
          // Create GitHub comment for tracking (only for pull requests)
          if (context.eventName === 'pull_request') {
            try {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });
              console.log('✅ Failure comment created on PR');
            } catch (error) {
              // Graceful fallback if permissions are insufficient
              console.log('⚠️ Could not create PR comment (this is normal for some permissions)');
              console.log('Error details:', error.message);
            }
          }

    # Only send email if recipient is specified
    - name: Send email notification
      if: inputs.email-to != ''
      uses: dawidd6/action-send-mail@v6
      with:
        server_address: smtp.gmail.com
        server_port: 587
        secure: false
        username: ${{ inputs.brevo-smtp-user }}
        password: ${{ inputs.brevo-smtp-key }}
        subject: "❌ ${{ inputs.environment }} Deployment Failed - ${{ github.repository }}"
        from: "<shalommeoded@gmail.com>"
        to: ${{ inputs.email-to }}
        body: |
          Hello ${{ github.actor }},
          
          Your deployment to ${{ inputs.environment }} environment has failed!
          
          **Details:**
          - Repository: ${{ github.repository }}
          - Branch: ${{ github.ref_name }}
          - Version: ${{ inputs.version }}
          - Commit: ${{ github.sha }}
          - Environment: ${{ inputs.environment }}
          - Error: ${{ inputs.error }}
          
          🔧 Please check the [workflow logs](${{ github.serverUrl }}/${{ github.repository }}/actions/runs/${{ github.runId }}) for details.
          
          Best regards,
          CI/CD Pipeline
        convert_markdown: true
