name: 'Docker Build & Push'
description: 'Build and push Docker image to registry'

inputs:
  registry:
    description: 'Docker registry URL'
    required: true
    default: 'docker.io'
  image-name:
    description: 'Docker image name'
    required: true
  username:
    description: 'Docker registry username'
    required: true
  password:
    description: 'Docker registry password'
    required: true
  version:
    description: 'Version tag for the Docker image'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.version }}
          ${{ inputs.registry }}/${{ inputs.image-name }}:latest
        labels: |
          org.opencontainers.image.version=${{ inputs.version }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.revision=${{ github.sha }}
