name: 'Generate Release'
description: 'Generate release notes and create GitHub release'

inputs:
  tag-name:
    description: 'Tag name for the release'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate release notes
      shell: bash
      run: |
        echo "## 🚀 Release ${{ inputs.tag-name }}" > release_notes.md
        echo "" >> release_notes.md
        echo "### 📦 What's New" >> release_notes.md
        echo "" >> release_notes.md
        git log --oneline $(git describe --tags --abbrev=0 HEAD^)..HEAD >> release_notes.md
        echo "" >> release_notes.md
        echo "### 🔒 Security" >> release_notes.md
        echo "- Vulnerability scanning completed" >> release_notes.md
        echo "- Container image built and pushed" >> release_notes.md
        echo "" >> release_notes.md
        echo "### 📊 Quality" >> release_notes.md
        echo "- All tests passing" >> release_notes.md
        echo "- Code quality gates passed" >> release_notes.md

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.tag-name }}
        release_name: Release ${{ inputs.tag-name }}
        body_path: release_notes.md
        draft: false
        prerelease: false

    - name: Release Summary
      shell: bash
      run: |
        echo "## 🎉 Release ${{ inputs.tag-name }} Published" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Artifacts" >> $GITHUB_STEP_SUMMARY
        echo "- **Docker Image**: Built and pushed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔒 Security" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Vulnerability scanning completed" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Container image built and pushed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Quality" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ All tests passing" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Code quality gates passed" >> $GITHUB_STEP_SUMMARY
