name: Release

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/it-works-on-my-machine

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    environment: main
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and push Docker image
      uses: ./.github/actions/docker-build
      with:
        registry: ${{ env.REGISTRY }}
        image-name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate release
      uses: ./.github/actions/generate-release
      with:
        tag-name: ${{ github.ref_name }}
