name: Emergency Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      environment:
        description: 'Environment to rollback'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      reason:
        description: 'Reason for rollback'
        required: true
        default: 'Health check failures'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/it-works-on-my-machine

jobs:
  rollback:
    name: Rollback to ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate and checkout version
      uses: ./.github/actions/validate-version
      with:
        version: ${{ github.event.inputs.version }}

    - name: Generate rollback version tag
      id: version
      run: |
        # Create rollback version with -rollback suffix
        ROLLBACK_VERSION="${{ github.event.inputs.version }}-rollback"
        echo "rollback_version=${ROLLBACK_VERSION}" >> $GITHUB_OUTPUT
        echo "base_version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        echo "Generated rollback version: ${ROLLBACK_VERSION}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push rollback image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.rollback_version }}
        labels: |
          org.opencontainers.image.version=${{ steps.version.outputs.rollback_version }}
          org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          org.opencontainers.image.revision=${{ github.sha }}

    - name: Deploy rollback
      uses: ./.github/actions/rollback-deploy
      with:
        version: ${{ github.event.inputs.version }}
        environment: ${{ github.event.inputs.environment }}
        reason: ${{ github.event.inputs.reason }}
        registry: ${{ env.REGISTRY }}
        image-name: ${{ env.IMAGE_NAME }}

    - name: Create rollback issue
      uses: ./.github/actions/create-rollback-issue
      with:
        version: ${{ github.event.inputs.version }}
        environment: ${{ github.event.inputs.environment }}
        reason: ${{ github.event.inputs.reason }}
        registry: ${{ env.REGISTRY }}
        image-name: ${{ env.IMAGE_NAME }}
